"""
スキーマ統合モジュール - 後方互換性のため
"""
# 共通スキーマ
from schemas.shared import (
    ApplicationStatus,
    PostStatus,
    NoticeStatus,
    NoticePriority,
    LoginRequest,
    TokenResponse,
    MessageResponse,
    CalendarRequest,
    TagResponse,
)

# ユーザー側スキーマ
from schemas.user import (
    RegisterRequest,
    RegisterDbRequest,
    UserRegisterResponse,
    ApplicationStatusResponse as UserApplicationStatusResponse,
    UpdateUserProfileRequest,
    UpdateUserDbRequest,
    UserDbResponse,
    UserProfileDetailResponse,
    AddDogRequest,
    CreateDogDbRequest,
    UpdateDogDbRequest,
    DogDbResponse,
    VaccinationRecordRequest,
    VaccinationRecordResponse,
    CreatePostRequest,
    CreatePostDbRequest,
    PostDbResponse,
    PostDetailResponse,
    AddCommentRequest,
    CreateCommentDbRequest,
    CommentDbResponse,
    EventResponse,
    EventDetailResponse,
    EventRegistrationRequest,
    EventParticipantResponse,
    QRCodeResponse,
    EntryRequest,
    EntryResponse,
    CurrentVisitorsResponse,
    EntryHistoryResponse,
)

# 管理側スキーマ
from schemas.admin import (
    AdminRole,
    AdminLoginRequest,
    AdminUserResponse,
    AdminLoginResponse,
    AdminUserCreateRequest,
    AdminUserUpdateRequest,
    ApplicationResponse,
    ApplicationUpdateRequest,
    ApplicationCreateRequest,
    ApplicationStatusResponse as AdminApplicationStatusResponse,
    AdminLogResponse,
    PostManagementResponse,
    PostStatusUpdateRequest,
    UserStatsResponse,
    UserDetailResponse,
    UserSuspendRequest,
    EventCreateRequest,
    EventUpdateRequest,
    EventManagementResponse,
    EventStatsResponse,
    EventRegistrationResponse,
    NoticeCreateRequest,
    NoticeUpdateRequest,
    NoticeManagementResponse,
    BusinessHourResponse,
    BusinessHourUpdateRequest,
    SpecialHolidayResponse,
    SpecialHolidayCreateRequest,
    SpecialHolidayUpdateRequest,
    TodayBusinessHoursResponse,
    SystemSettingResponse,
    SystemSettingUpdateRequest,
    SystemSettingsCategoryResponse,
    SystemSettingsBackupResponse,
    SystemSettingsImportRequest,
    DashboardStatsResponse,
)

# 後方互換性のため、ApplicationStatusResponseを統合
ApplicationStatusResponse = UserApplicationStatusResponse

__all__ = [
    # 共通
    "ApplicationStatus",
    "PostStatus",
    "NoticeStatus",
    "NoticePriority",
    "LoginRequest",
    "TokenResponse",
    "MessageResponse",
    "CalendarRequest",
    "TagResponse",
    # ユーザー側
    "RegisterRequest",
    "RegisterDbRequest",
    "UserRegisterResponse",
    "ApplicationStatusResponse",
    "UpdateUserProfileRequest",
    "UpdateUserDbRequest",
    "UserDbResponse",
    "UserProfileDetailResponse",
    "AddDogRequest",
    "CreateDogDbRequest",
    "UpdateDogDbRequest",
    "DogDbResponse",
    "VaccinationRecordRequest",
    "VaccinationRecordResponse",
    "CreatePostRequest",
    "CreatePostDbRequest",
    "PostDbResponse",
    "PostDetailResponse",
    "AddCommentRequest",
    "CreateCommentDbRequest",
    "CommentDbResponse",
    "EventResponse",
    "EventDetailResponse",
    "EventRegistrationRequest",
    "EventParticipantResponse",
    "QRCodeResponse",
    "EntryRequest",
    "EntryResponse",
    "CurrentVisitorsResponse",
    "EntryHistoryResponse",
    # 管理側
    "AdminRole",
    "AdminLoginRequest",
    "AdminUserResponse",
    "AdminLoginResponse",
    "AdminUserCreateRequest",
    "AdminUserUpdateRequest",
    "ApplicationResponse",
    "ApplicationUpdateRequest",
    "ApplicationCreateRequest",
    "AdminLogResponse",
    "PostManagementResponse",
    "PostStatusUpdateRequest",
    "UserStatsResponse",
    "UserDetailResponse",
    "UserSuspendRequest",
    "EventCreateRequest",
    "EventUpdateRequest",
    "EventManagementResponse",
    "EventStatsResponse",
    "EventRegistrationResponse",
    "NoticeCreateRequest",
    "NoticeUpdateRequest",
    "NoticeManagementResponse",
    "BusinessHourResponse",
    "BusinessHourUpdateRequest",
    "SpecialHolidayResponse",
    "SpecialHolidayCreateRequest",
    "SpecialHolidayUpdateRequest",
    "TodayBusinessHoursResponse",
    "SystemSettingResponse",
    "SystemSettingUpdateRequest",
    "SystemSettingsCategoryResponse",
    "SystemSettingsBackupResponse",
    "SystemSettingsImportRequest",
    "DashboardStatsResponse",
]

